name: E2E Tests

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  

permissions:
  statuses: write

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: check out repo
        uses: actions/checkout@v4

      - name: set up node${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Log test run details
        if: always()
        run: |
          echo "Results for $BASE_URL" >> $GITHUB_STEP_SUMMARY
          
      - name: run cypress
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev

      - name: Report success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: 'marissahuysentruyt',
              repo: 'estimate-tracker',
              sha: '${{ github.event.pull_request.head.sha }}',
              state: 'success',
              description: 'Cypress tests passed!',
              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

      - name: report failures
        if: (failure() || cancelled())
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: 'marissahuysentruyt',
              repo: 'estimate-tracker',
              sha: '${{github.event.pull_request.head.sha }}',
              state: 'error',
              description: 'Cypress tests failed (check logs for details)',
              target_url: '${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}'
            })
