name: Lint

on:
  # trigger linting when pushing to the main branch
  push:
    branches:
      - main

  # trigger linting when creating a PR against the main branch
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: check out repo
        uses: actions/checkout@v4

      - name: set up node${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install dependencies
        run: npm ci

      - name: run linters
        run: npm run lint

